#! /bin/sh

### Autostart ###
sxhkd &
compton &
~/.config/bspwm/launch.sh &

### Monitors ###
bspc monitor HDMI-1 -d I II III
bspc monitor DP-0 -d I II III 

### Config ###
bspc config border_width         2
bspc config window_gap          12
bspc config top_padding		20
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config split_ratio          0.52
bspc config single_monocle       false
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config focus_follows_pointer true

### BSPWM Coloring ###
bspc config normal_border_color  "#4c566a"
bspc config active_border_color  "#1e1e1e"

### Rules ###
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
