#!/bin/sh

# function to get the x resources
xresource() {
  xrdb -query | grep -E "^(bspwm|\*)\.$1" | sed -r "s/^[^:]+:\s+//" | tail -n 1
}

pgrep -x sxhkd > /dev/null || sxhkd &

#
# (Order is important. More important monitors first. (Like if VGA1 is attached to
#  laptop, it should be the main monitor, not LVDS1, so VGA1 is before LVDS1.))
monitors=('DP-2' 'DP-1' 'DP-0' 'HDMI-1' 'HDMI-0' 'DVI-D-1' 'DVI-0' 'DVI-1' 'VGA1' 'LVDS1' 'LVDS-1' )
i=1
for m in ${monitors[@]}; do
 if bspc query -M | grep "$m"; then
   bspc monitor $m -d $i-{1..9}
   if [[ "$i" -eq 1 ]]; then
     xrandr --output $m --primary
   fi
   let i++
 fi
done

bspc monitor DP-2 -d I II III
bspc monitor DP-0 -d IV V VI

#bspc wm --reorder-monitors HDMI-1

bspc config border_width         3
bspc config window_gap          16

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config automatic_scheme longest_side

###########################
#  ____        _
# |  _ \ _   _| | ___  ___
# | |_) | | | | |/ _ \/ __|
# |  _ <| |_| | |  __/\__ \
# |_| \_\\__,_|_|\___||___/
###########################
bspc rule --add Gimp desktop='III' state=floating follow=on
bspc rule --add TelegramDesktop desktop='IV'
bspc rule --add Screenkey manage=off
bspc rule --add vlc state=floating follow=on
bspc rule --add Signal:signal desktop='IV' follow=off foxus off

# floating windows
bspc rule --add Pavucontrol state=floating
bspc rule --add feh state=floating
bspc rule --add Evince state=floating focus=on
bspc rule --add Lutris state=floating focus=on
bspc rule --add Back In Time state=floating focus=on
bspc rule --add Steam state=floating focus=on
bspc rule --add git-gui state=floating
bspc rule --add qemu-system-x86_64 state=floating

# pseudo tiled
bspc rule -add Steam state=pseudo_tiled

# Add further rules
bspc config external_rules_command ~/.config/bspwm/external_rules.sh

##############################
#  ____      _
# / ___|___ | | ___  _ __ ___
#| |   / _ \| |/ _ \| '__/ __|
#| |__| (_) | | (_) | |  \__ \
# \____\___/|_|\___/|_|  |___/
##############################
bspc config focused_border_color $(xresource color3)
bspc config active_border_color $(xresource foreground)
bspc config normal_border_color $(xresource foreground-alt)

## Desktop environment
#

# launch polybar
$HOME/.config/polybar/launch.sh

# source background
source $HOME/.fehbg

# launch compositor
picom

# launch notification manager
dunst

