require "plugins/nvim-cmp"
require "plugins/nvim-lspconfig"
require "plugins/nvim-treesitter"
require "plugins/alpha-nvim"
require "plugins/nvim-tree"
require "plugins/telescope"
require "plugins/nvim-autopairs"
require "plugins/lsp"
