require("plugins/neotree")
require("plugins/bufferline")
require("plugins/lualine")
require("plugins/nvim-cmp")
require("plugins/nvim-treesitter")
require("plugins/telescope")
require("plugins/alpha-nvim")
require("plugins/nvim-autopairs")
require("plugins/galaxyline")

-- This is broken as of 0.9.0
-- require("plugins/nvim-gps")

require("plugins/neoscroll")
require("plugins/diffview")
require("plugins/neovim-session-manager")
require("plugins/nvim-dap")
require("plugins/nvim-dap-ui")
require("plugins/indent-blankline")
require("plugins/gitsigns")
require("plugins/just")
require("plugins/git-worktree")
require("plugins/leap")
require("plugins/tabby")
require("plugins/nvim-colorizer")
-- require("plugins/nvim-cokeline")

require("plugins/lsp")
require("plugins/dap")
