theme = "bogster"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.lsp]
display-inlay-hints = true
display-signature-help-docs = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
